feat: Add --arm64 flag which will use rust-optimizer-arm64 for optimization.
terra-money/terrain pull request #7
Opened 2022-04-04 19:57 UTC by octalmage

During the Ottawa hackathon we heard feedback that the deploy process was slow and painful when using m1 hardware. This is due to the emulation used when running rust-optimizer. So we should include a new flag, `--arm64` that will let the developer use `rust-optimizer-arm64` when appropriate, but builds produced should only be used during development. 

From the readme of rust-optimizer: 

> However, the native Arm version produces different wasm artifacts than the Intel version. Given that that impacts reproducibility, non-Intel images and build artifacts contain a "-arm64" suffix, to differentiate and flag them.

> Arm images are released to ease development and testing on Mac M1 machines. For release / production use, only contracts built with the Intel optimizers must be used.

2022-04-04 20:00 UTC, octalmage commented
To test: 

```
terrain deploy counter --signer test1 --arm64
```

2022-04-05 07:28 UTC, emidev98 commented on src/commands/deploy.ts
> +    }),
Is there maybe a way to throw an error or warn when the user tries to use this build with production deployment combined?

2022-04-05 16:52 UTC, rtviii requested changes
Yeah i don't really see how this is for us to fix. 
let's just warn for mainnet. anyone who is deploying critical code to columbus should be able to get an x86 machine and hopefully know what they are doing.

2022-04-06 01:15 UTC, rtviii approved these changes

2022-04-07 20:55 UTC, merged

2022-04-11 16:04 UTC, sascha1337 commented
agreed, please warn the people, Ethan Frey and others clearly said use x86, ill do some static/dyn analysis / fuzzing stuff on same contract code, but different targets, arm64wasm vs x86wasm, 

lets find out what exactly the differences are, if they are critical nature or just some harmless different placed instructions, but execution call flow is the same for example. And I'm gonna ask in the rust workgroup too